services:
    database:
        container_name: management_db
        image: postgres:17.4-alpine
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
        ports:
            -   "5432:5432"
        volumes:
            -   management_volume:/var/lib/postgresql/data
volumes:
    management_volume:
        driver: local
